apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-cypress
    labels:
        app: hello-cypress
spec:
    replicas: 2
    selector:
        matchLabels: 
            app: hello-cypress
    template:
        metadata:
            labels:
                app: hello-cypress
        spec:
            containers:
            -   name: hello-cypress
                image: magnolialabs/hello-cypress
                ports:
                -   containerPort: 80 
                resources:
                    limits:
                        memory: '128Mi'
                        cpu: '200m'
                livenessProbe:
                    httpGet:
                        path: /index.html
                        port: 80
                    initialDelaySeconds: 15
                    timeoutSeconds: 2
                    periodSeconds: 5
                    failureThreshold: 1
                readinessProbe:
                    httpGet:
                        path: /index.html
                        port: 80
                    initialDelaySeconds: 15
                    periodSeconds: 5
                    failureThreshold: 1